[profile.release]
lto = "fat"
panic = "abort"
opt-level = 'z'
incremental = false
codegen-units = 1

[workspace]
members = [ "login_ng", "login_ng_user_interactions", "pam_login_ng", "login_ng-cli", "login_ng-ctl" ]
resolver = "2"