[package]
name = "login_ng"
version = "0.1.44"
edition = "2021"
license = "GPL-2.0-or-later"

[dependencies]
users = "0.11.0"
thiserror = "^1.0"
aes-gcm = "^0.10"
bcrypt = "^0.15"
hkdf = { version = "^0.12", features = [] }
sha2 = "0.10.8"
xattr = "1.3.1"
bytevec2 = "0.3.1"
rs_sha512 = "0.1.3"
